# Clean and preprocess the dataset

Import dataset and libraries

In [38]:
import pandas as pd
import numpy as np

In [39]:
Df_dataset = pd.read_csv("Student_performance.csv")
Df_dataset.head()

roll_no gender race_ethnicity parental_level_of_education  lunch  \
0  std-01   male        group D                some college    1.0   
1  std-02   male        group B                 high school    1.0   
2  std-03   male        group C             master's degree    1.0   
3  std-04   male        group D                some college    1.0   
4  std-05   male        group C                some college    0.0   

   test_preparation_course math_score  reading_score  writing_score  \
0                      1.0         89           38.0           85.0   
1                      0.0         65          100.0           67.0   
2                      0.0         10           99.0           97.0   
3                      1.0         22           51.0           41.0   
4                      1.0         26           58.0           64.0   

   science_score  total_score grade  
0           26.0        238.0     C  
1           96.0        328.0     A  
2           58.0        264.0     B  
3           84.0        198.0     D  
4           65.0        213.0     C

In [40]:
for column in Df_dataset.columns:
  print(f"Unique values in column '{column}':")
  print(Df_dataset[column].unique())
  print("-" * 30)

Unique values in column 'roll_no':
['std-01' 'std-02' 'std-03' ... 'std-9998' 'std-9999' 'std-10000']
------------------------------
Unique values in column 'gender':
['male' nan 'Boy' '\\tmale' 'female' 'Girl']
------------------------------
Unique values in column 'race_ethnicity':
['group D' 'group B' 'group C' 'group E' 'group A' 'A' nan 'C' 'D'
 'group C\\n' 'B' 'E']
------------------------------
Unique values in column 'parental_level_of_education':
['some college' 'high school' "master's degree" "associate's degree" nan
 'some high school' "bachelor's degree"]
------------------------------
Unique values in column 'lunch':
[ 1.  0. nan]
------------------------------
Unique values in column 'test_preparation_course':
[ 1.  0. nan]
------------------------------
Unique values in column 'math_score':
['89' '65' '10' '22' '26' '40' '34' '25' '28' '71' '55' nan '29' '18' '72'
 '23' '35' '38' '41' '44' '39' '85' '30' '100' '61' '47' '37' '49' '11'
 '32' '78' '36' '68' '97' '64' '60'

gender organize

In [41]:
Df_dataset['gender'] = Df_dataset['gender'].replace(['Boy', '\\tmale'], 'male')
Df_dataset['gender'] = Df_dataset['gender'].replace('Girl', 'female')

print(Df_dataset['gender'].unique())

['male' nan 'female']


In [42]:
Df_dataset["gender"] = Df_dataset["gender"].fillna("Unknown")

race_ethicity

In [43]:
Df_dataset['race_ethnicity'] = Df_dataset['race_ethnicity'].replace(['A', 'B', 'C', 'D', 'E'], ['group A', 'group B', 'group C', 'group D', 'group E'])
Df_dataset['race_ethnicity'] = Df_dataset['race_ethnicity'].str.replace('\\n', '', regex=False)
Df_dataset['race_ethnicity'] = Df_dataset['race_ethnicity'].fillna('Unknown')

print(Df_dataset['race_ethnicity'].unique())

['group D' 'group B' 'group C' 'group E' 'group A' 'Unknown']


In [44]:
race_ethnicity_counts = Df_dataset['race_ethnicity'].value_counts()
print(race_ethnicity_counts)

race_ethnicity
group C    2928
group D    2572
group B    1900
group E    1513
group A    1064
Unknown      23
Name: count, dtype: int64


The race_ethnicity column was dropped since the dataset used anonymized groups (A–E) that do not reflect Sri Lanka’s real demographic structure. To avoid misleading patterns, we excluded this feature in training.

In [45]:
Df_dataset = Df_dataset.drop('race_ethnicity', axis=1)
display(Df_dataset.head())

roll_no gender parental_level_of_education  lunch  test_preparation_course  \
0  std-01   male                some college    1.0                      1.0   
1  std-02   male                 high school    1.0                      0.0   
2  std-03   male             master's degree    1.0                      0.0   
3  std-04   male                some college    1.0                      1.0   
4  std-05   male                some college    0.0                      1.0   

  math_score  reading_score  writing_score  science_score  total_score grade  
0         89           38.0           85.0           26.0        238.0     C  
1         65          100.0           67.0           96.0        328.0     A  
2         10           99.0           97.0           58.0        264.0     B  
3         22           51.0           41.0           84.0        198.0     D  
4         26           58.0           64.0           65.0        213.0     C

parental_level_of_education

In [46]:
Df_dataset['parental_level_of_education'] = Df_dataset['parental_level_of_education'].replace('some high school', 'high school')
Df_dataset['parental_level_of_education'] = Df_dataset['parental_level_of_education'].fillna('Unknown')
display(Df_dataset['parental_level_of_education'].unique())

array(['some college', 'high school', "master's degree",
       "associate's degree", 'Unknown', "bachelor's degree"], dtype=object)

lunch and test_preparation_course

take the mode value for missing values

In [47]:
lunch_mode = Df_dataset['lunch'].mode()[0]
Df_dataset['lunch'] = Df_dataset['lunch'].fillna(lunch_mode)
Df_dataset['lunch'] = Df_dataset['lunch'].astype(int)

test_prep_mode = Df_dataset['test_preparation_course'].mode()[0]
Df_dataset['test_preparation_course'] = Df_dataset['test_preparation_course'].fillna(test_prep_mode)
Df_dataset['test_preparation_course'] = Df_dataset['test_preparation_course'].astype(int)

print("Unique values in 'lunch' column:")
print(Df_dataset['lunch'].unique())
print("-" * 30)
print("Unique values in 'test_preparation_course' column:")
print(Df_dataset['test_preparation_course'].unique())

Unique values in 'lunch' column:
[1 0]
------------------------------
Unique values in 'test_preparation_course' column:
[1 0]


**scores**

---
Get median as missing value for 'math_score', 'reading_score', 'writing_score', 'science_score'
re calculate total score with sum of above scores

In [48]:
for col in ['math_score', 'reading_score', 'writing_score', 'science_score']:
  # Remove '\t' if present
  Df_dataset[col] = Df_dataset[col].astype(str).str.replace('\\t', '', regex=False)
  # Convert to numeric, coercing errors to NaN
  Df_dataset[col] = pd.to_numeric(Df_dataset[col], errors='coerce')
  # Fill NaN with the median
  median_val = Df_dataset[col].median()
  Df_dataset[col] = Df_dataset[col].fillna(median_val)

print("Unique values in 'math_score' column after cleaning:")
print(Df_dataset['math_score'].unique())
print("-" * 30)
print("Unique values in 'reading_score' column after cleaning:")
print(Df_dataset['reading_score'].unique())
print("-" * 30)
print("Unique values in 'writing_score' column after cleaning:")
print(Df_dataset['writing_score'].unique())
print("-" * 30)
print("Unique values in 'science_score' column after cleaning:")
print(Df_dataset['science_score'].unique())

Unique values in 'math_score' column after cleaning:
[ 89.  65.  10.  22.  26.  40.  34.  25.  28.  71.  55.  58.  29.  18.
  72.  23.  35.  38.  41.  44.  39.  85.  30. 100.  61.  47.  37.  49.
  11.  32.  78.  36.  68.  97.  64.  60.  69.  87.  83.  42.  52.  27.
  46.  12.  51.  75.  20.  81.  98.  24.  82.  19.  48.  74.  43.  62.
  21.  93.  66.   0.  13.  45.  57.  54.  70.  50.  73.  88.  33.  76.
  17.  16.  56.  80.  53.  14.  84.   9.   8.  79.  77.  99.  67.  59.
  63.  86.  31.  92.  94.   6.  91.  96.  95.  15.  90.   7.   4.   5.]
------------------------------
Unique values in 'reading_score' column after cleaning:
[ 38. 100.  99.  51.  58.  49.  48.  80.  79.  22.  64.  53.  71.  70.
  97.  96.  82.  76.  73.  68.  63.  57.  54.  89.  69.  67.  77.  66.
  92.  81.  43.  56.  90.  98.  55.  91.  83.  86.  88.  40.  62.  30.
  60.  65.  85.  37.  78.  84.  74.  95.  47.  59.  44.  72.  17.  34.
  87.  93.  41.  36.  75.  50.  52.  46.  45.  39.  94.  61.  35.  33.
  31.  

In [49]:
Df_dataset['total_score'] = Df_dataset.apply(
    lambda row: row['math_score'] + row['reading_score'] + row['writing_score'] + row['science_score'] if pd.isna(row['total_score']) else row['total_score'],
    axis=1
)

print("Unique values in 'total_score' column after cleaning:")
print(Df_dataset['total_score'].unique())

Unique values in 'total_score' column after cleaning:
[238. 328. 264. 198. 213. 206. 239. 156. 283. 217. 266. 228. 293. 162.
 289. 207. 275. 280. 224. 208. 195. 237. 282. 165. 307. 250. 240. 233.
 242. 306. 178. 169. 247. 292. 256. 319. 316. 252. 215. 313. 297. 212.
 261. 241. 311. 253. 272. 257. 298. 248. 220. 236. 232. 284. 270. 230.
 369. 221. 288. 302. 268. 301. 249. 210. 176. 285. 246. 182. 304. 229.
 231. 255. 305. 243. 287. 188. 193. 327. 340. 191. 218. 273. 314. 197.
 225. 321. 300. 203. 172. 234. 335. 320. 324. 166. 317. 294. 140. 274.
 352. 281. 310. 265. 192. 183. 194. 204. 308. 258. 309. 296. 278. 199.
 262. 269. 190. 322. 267. 124. 219. 276. 303. 201. 226. 254. 196. 260.
 171. 235. 227. 146. 211. 271. 214. 205. 277. 216. 209. 263. 318. 185.
 355. 325. 164. 222. 157. 147. 330. 179. 115. 291. 295. 371. 360. 329.
 177. 251. 202. 141. 244. 334. 326. 331. 187. 312. 337. 150. 245. 121.
 155. 139. 186. 135. 223. 336. 343. 290. 323. 362. 200. 189. 170. 346.
 315. 259. 339. 127. 18

In [50]:
# Calculate what the total should be
Df_dataset['calculated_total'] = (
    Df_dataset['math_score'] +
    Df_dataset['reading_score'] +
    Df_dataset['writing_score'] +
    Df_dataset['science_score']
)

# Identify the rows with mismatches
mismatch_indices = Df_dataset[Df_dataset['total_score'] != Df_dataset['calculated_total']].index

# Update the 'total_score' with the 'calculated_total' for the mismatch rows
Df_dataset.loc[mismatch_indices, 'total_score'] = Df_dataset.loc[mismatch_indices, 'calculated_total']

# Verify that the mismatches are fixed
mismatches_after_correction = Df_dataset[Df_dataset['total_score'] != Df_dataset['calculated_total']]

print("Number of mismatches after correction:", len(mismatches_after_correction))
# You can display the mismatches_after_correction DataFrame if you want to double-check
# print(mismatches_after_correction[['math_score','reading_score','writing_score','science_score','total_score','calculated_total']])

Number of mismatches after correction: 0


In [51]:
display(Df_dataset.head())

roll_no gender parental_level_of_education  lunch  test_preparation_course  \
0  std-01   male                some college      1                        1   
1  std-02   male                 high school      1                        0   
2  std-03   male             master's degree      1                        0   
3  std-04   male                some college      1                        1   
4  std-05   male                some college      0                        1   

   math_score  reading_score  writing_score  science_score  total_score grade  \
0        89.0           38.0           85.0           26.0        238.0     C   
1        65.0          100.0           67.0           96.0        328.0     A   
2        10.0           99.0           97.0           58.0        264.0     B   
3        22.0           51.0           41.0           84.0        198.0     D   
4        26.0           58.0           64.0           65.0        213.0     C   

   calculated_total  
0             238.0  
1             328.0  
2             264.0  
3             198.0  
4             213.0

In [52]:
Df_dataset = Df_dataset.drop(['roll_no', 'calculated_total'], axis=1)
display(Df_dataset.head())

gender parental_level_of_education  lunch  test_preparation_course  \
0   male                some college      1                        1   
1   male                 high school      1                        0   
2   male             master's degree      1                        0   
3   male                some college      1                        1   
4   male                some college      0                        1   

   math_score  reading_score  writing_score  science_score  total_score grade  
0        89.0           38.0           85.0           26.0        238.0     C  
1        65.0          100.0           67.0           96.0        328.0     A  
2        10.0           99.0           97.0           58.0        264.0     B  
3        22.0           51.0           41.0           84.0        198.0     D  
4        26.0           58.0           64.0           65.0        213.0     C

#encoding

label encoder for gender,
ordinal encoder for parental_level_of_education

In [53]:
from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder
label_encoder = LabelEncoder()

# Fit and transform the 'gender' column
Df_dataset['gender_encoded'] = label_encoder.fit_transform(Df_dataset['gender'])

# Display the mapping
print("Gender mapping:")
for i, item in enumerate(label_encoder.classes_):
    print(f"{item}: {i}")

# Display the head of the dataframe with the new column
display(Df_dataset.head())

Gender mapping:
Unknown: 0
female: 1
male: 2


gender parental_level_of_education  lunch  test_preparation_course  \
0   male                some college      1                        1   
1   male                 high school      1                        0   
2   male             master's degree      1                        0   
3   male                some college      1                        1   
4   male                some college      0                        1   

   math_score  reading_score  writing_score  science_score  total_score grade  \
0        89.0           38.0           85.0           26.0        238.0     C   
1        65.0          100.0           67.0           96.0        328.0     A   
2        10.0           99.0           97.0           58.0        264.0     B   
3        22.0           51.0           41.0           84.0        198.0     D   
4        26.0           58.0           64.0           65.0        213.0     C   

   gender_encoded  
0               2  
1               2  
2               2  
3               2  
4               2

In [54]:
from sklearn.preprocessing import OrdinalEncoder

# Define the order of the educational levels
education_order = [
    'Unknown',
    'high school',
    'some college',
    "associate's degree",
    "bachelor's degree",
    "master's degree"
]

# Initialize OrdinalEncoder with the specified order
ordinal_encoder = OrdinalEncoder(categories=[education_order])

# Fit and transform the 'parental_level_of_education' column
Df_dataset['parental_education_encoded'] = ordinal_encoder.fit_transform(Df_dataset[['parental_level_of_education']])

# Display the head of the dataframe with the new column
display(Df_dataset.head())

gender parental_level_of_education  lunch  test_preparation_course  \
0   male                some college      1                        1   
1   male                 high school      1                        0   
2   male             master's degree      1                        0   
3   male                some college      1                        1   
4   male                some college      0                        1   

   math_score  reading_score  writing_score  science_score  total_score grade  \
0        89.0           38.0           85.0           26.0        238.0     C   
1        65.0          100.0           67.0           96.0        328.0     A   
2        10.0           99.0           97.0           58.0        264.0     B   
3        22.0           51.0           41.0           84.0        198.0     D   
4        26.0           58.0           64.0           65.0        213.0     C   

   gender_encoded  parental_education_encoded  
0               2                         2.0  
1               2                         1.0  
2               2                         5.0  
3               2                         2.0  
4               2                         2.0

In [55]:
print("Missing values per column:")
print(Df_dataset.isnull().sum())
print("-" * 30)

print("\nData types of each column:")
print(Df_dataset.dtypes)
print("-" * 30)

print("\nValue counts for 'grade' column (checking for imbalance):")
print(Df_dataset['grade'].value_counts())

Missing values per column:
gender                         0
parental_level_of_education    0
lunch                          0
test_preparation_course        0
math_score                     0
reading_score                  0
writing_score                  0
science_score                  0
total_score                    0
grade                          3
gender_encoded                 0
parental_education_encoded     0
dtype: int64
------------------------------

Data types of each column:
gender                          object
parental_level_of_education     object
lunch                            int32
test_preparation_course          int32
math_score                     float64
reading_score                  float64
writing_score                  float64
science_score                  float64
total_score                    float64
grade                           object
gender_encoded                   int32
parental_education_encoded     float64
dtype: object
-----------------------

In [56]:
score_cols = ['math_score','reading_score','writing_score','science_score','total_score']

# 1) Simple ranges (min/max) and basic stats
print(Df_dataset[score_cols].agg(['count','min','max','mean','std','median']).T)

# 2) Percentile range (robust sense of spread)
q = Df_dataset[score_cols].quantile([0, .01, .05, .25, .5, .75, .95, .99, 1.0]).T
print(q)

# 3) Check domain violations (subjects should be 0–100, total 0–400)
for c in ['math_score','reading_score','writing_score','science_score']:
    bad = Df_dataset[(Df_dataset[c] < 0) | (Df_dataset[c] > 100)]
    print(f"{c}: {len(bad)} values outside 0–100")
bad_total = Df_dataset[(Df_dataset['total_score'] < 0) | (Df_dataset['total_score'] > 400)]
print(f"total_score: {len(bad_total)} values outside 0–400")

# 4) Quick histograms (textual bins) to see distribution shape
score_bins = [0, 50, 60, 70, 80, 90, 101] # Use 101 to include 100
total_bins = [0, 50, 100, 150, 200, 250, 300, 350, 401] # Use 401 to include 400

for c in score_cols:
    print(f"\n{c} bins:")
    if c == 'total_score':
        print(pd.cut(Df_dataset[c], bins=total_bins, right=False).value_counts().sort_index())
    else:
        print(pd.cut(Df_dataset[c], bins=score_bins, right=False).value_counts().sort_index())


# 5) If you want min/max by grade too (sanity check):
if 'grade' in Df_dataset.columns:
    print("\nMin/Max Total Score by Grade:")
    print(Df_dataset.groupby('grade')['total_score'].agg(['min','max']))

                 count   min    max      mean        std  median
math_score     10000.0   0.0  100.0   57.1791  21.720700    58.0
reading_score  10000.0  17.0  100.0   70.1281  19.002495    71.0
writing_score  10000.0  10.0  100.0   71.4184  18.223527    72.5
science_score  10000.0   9.0  100.0   66.0652  19.302145    67.0
total_score    10000.0  89.0  383.0  264.7908  42.253301   268.0
               0.00   0.01   0.05   0.25   0.50   0.75   0.95   0.99   1.00
math_score      0.0   11.0   21.0   41.0   58.0   73.0   93.0  100.0  100.0
reading_score  17.0   23.0   37.0   57.0   71.0   85.0  100.0  100.0  100.0
writing_score  10.0   27.0   39.0   59.0   72.5   85.0  100.0  100.0  100.0
science_score   9.0   15.0   34.0   53.0   67.0   81.0   97.0  100.0  100.0
total_score    89.0  160.0  190.0  238.0  268.0  294.0  330.0  351.0  383.0
math_score: 0 values outside 0–100
reading_score: 0 values outside 0–100
writing_score: 0 values outside 0–100
science_score: 0 values outside 0–100
total

get the grade according to the determine pattern of total score

In [57]:
# Define the grading function
def grade_from_total(t):
    if pd.isna(t): return np.nan
    t = float(t)
    if t >= 320: return 'A'
    elif t >= 250: return 'B'
    elif t >= 200: return 'C'
    elif t >= 150: return 'D'
    else: return 'Fail'

# Apply the function to calculate a new grade column
Df_dataset['calculated_grade'] = Df_dataset['total_score'].apply(grade_from_total)

# Implement Option A: Replace the original 'grade' with the 'calculated_grade'
Df_dataset['grade'] = Df_dataset['calculated_grade']

# Drop the temporary 'calculated_grade' column
Df_dataset = Df_dataset.drop('calculated_grade', axis=1)

# Display the head of the dataframe with the updated 'grade' column
display(Df_dataset.head())

# Verify that there are no missing values in the grade column after this step
print("\nMissing values per column after implementing Option A:")
print(Df_dataset.isnull().sum())

gender parental_level_of_education  lunch  test_preparation_course  \
0   male                some college      1                        1   
1   male                 high school      1                        0   
2   male             master's degree      1                        0   
3   male                some college      1                        1   
4   male                some college      0                        1   

   math_score  reading_score  writing_score  science_score  total_score grade  \
0        89.0           38.0           85.0           26.0        238.0     C   
1        65.0          100.0           67.0           96.0        328.0     A   
2        10.0           99.0           97.0           58.0        264.0     B   
3        22.0           51.0           41.0           84.0        198.0     D   
4        26.0           58.0           64.0           65.0        213.0     C   

   gender_encoded  parental_education_encoded  
0               2                         2.0  
1               2                         1.0  
2               2                         5.0  
3               2                         2.0  
4               2                         2.0


Missing values per column after implementing Option A:
gender                         0
parental_level_of_education    0
lunch                          0
test_preparation_course        0
math_score                     0
reading_score                  0
writing_score                  0
science_score                  0
total_score                    0
grade                          0
gender_encoded                 0
parental_education_encoded     0
dtype: int64


In [58]:
display(Df_dataset.head())

gender parental_level_of_education  lunch  test_preparation_course  \
0   male                some college      1                        1   
1   male                 high school      1                        0   
2   male             master's degree      1                        0   
3   male                some college      1                        1   
4   male                some college      0                        1   

   math_score  reading_score  writing_score  science_score  total_score grade  \
0        89.0           38.0           85.0           26.0        238.0     C   
1        65.0          100.0           67.0           96.0        328.0     A   
2        10.0           99.0           97.0           58.0        264.0     B   
3        22.0           51.0           41.0           84.0        198.0     D   
4        26.0           58.0           64.0           65.0        213.0     C   

   gender_encoded  parental_education_encoded  
0               2                         2.0  
1               2                         1.0  
2               2                         5.0  
3               2                         2.0  
4               2                         2.0

In [59]:
from sklearn.preprocessing import OrdinalEncoder

# Define the order of the grades
grade_order = ['Fail', 'D', 'C', 'B', 'A']

# Initialize OrdinalEncoder with the specified order
ordinal_encoder_grade = OrdinalEncoder(categories=[grade_order])

# Fit and transform the 'grade' column
Df_dataset['grade_encoded'] = ordinal_encoder_grade.fit_transform(Df_dataset[['grade']])

# Display the head of the dataframe with the new column
display(Df_dataset.head())

gender parental_level_of_education  lunch  test_preparation_course  \
0   male                some college      1                        1   
1   male                 high school      1                        0   
2   male             master's degree      1                        0   
3   male                some college      1                        1   
4   male                some college      0                        1   

   math_score  reading_score  writing_score  science_score  total_score grade  \
0        89.0           38.0           85.0           26.0        238.0     C   
1        65.0          100.0           67.0           96.0        328.0     A   
2        10.0           99.0           97.0           58.0        264.0     B   
3        22.0           51.0           41.0           84.0        198.0     D   
4        26.0           58.0           64.0           65.0        213.0     C   

   gender_encoded  parental_education_encoded  grade_encoded  
0               2                         2.0            2.0  
1               2                         1.0            4.0  
2               2                         5.0            3.0  
3               2                         2.0            1.0  
4               2                         2.0            2.0

In [60]:
# Save the cleaned DataFrame to a CSV file
Df_dataset.to_csv('cleaned_student_data.csv', index=False)

# training model

In [61]:
%pip install imbalanced-learn
import pandas as pd, numpy as np, joblib
from sklearn.model_selection import train_test_split, StratifiedKFold, RandomizedSearchCV
from sklearn.metrics import precision_recall_curve, average_precision_score, roc_auc_score, classification_report
from sklearn.ensemble import RandomForestClassifier
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
from scipy.stats import randint, uniform

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.3.2 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [62]:
df = pd.read_csv("cleaned_student_data.csv")
df.head()

gender parental_level_of_education  lunch  test_preparation_course  \
0   male                some college      1                        1   
1   male                 high school      1                        0   
2   male             master's degree      1                        0   
3   male                some college      1                        1   
4   male                some college      0                        1   

   math_score  reading_score  writing_score  science_score  total_score grade  \
0        89.0           38.0           85.0           26.0        238.0     C   
1        65.0          100.0           67.0           96.0        328.0     A   
2        10.0           99.0           97.0           58.0        264.0     B   
3        22.0           51.0           41.0           84.0        198.0     D   
4        26.0           58.0           64.0           65.0        213.0     C   

   gender_encoded  parental_education_encoded  grade_encoded  
0               2                         2.0            2.0  
1               2                         1.0            4.0  
2               2                         5.0            3.0  
3               2                         2.0            1.0  
4               2                         2.0            2.0

In [63]:
df["at_risk"] = df["grade"].isin(["Fail","D"]).astype(int)

In [64]:
feat_cols = ["lunch","test_preparation_course","math_score","reading_score",
             "writing_score","science_score","gender_encoded","parental_education_encoded"]
X, y = df[feat_cols], df["at_risk"]

In [65]:
X, y = df[feat_cols], df["at_risk"]
Xtr, Xte, ytr, yte = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

Use SMOTE to handle data imbalance in at_risk and integrate SMOTE with RandomForestClassifier.

In [66]:
# Define the pipeline with SMOTE and RandomForestClassifier
pipeline = ImbPipeline([
    ('smote', SMOTE(random_state=42)),
    ('classifier', RandomForestClassifier(random_state=42))
])

# Define the parameter distribution for RandomizedSearchCV
param_dist = {
    'classifier__n_estimators': randint(100, 500),
    'classifier__max_depth': randint(3, 20),
    'classifier__min_samples_split': randint(2, 20),
    'classifier__min_samples_leaf': randint(1, 20),
    'classifier__bootstrap': [True, False],
    'smote__k_neighbors': randint(1, 10)
}

Use RandomizedSearchCV to find the best hyperparameters for the pipeline. This process will explore different combinations of the parameters defined in param_dist and evaluate their performance using cross-validation on training data.

---

ROC AUC are good choices as they are less affected by class imbalance than accuracy.


In [67]:
# Initialize RandomizedSearchCV
random_search = RandomizedSearchCV(
    pipeline,
    param_distributions=param_dist,
    n_iter=50,  # Number of parameter settings that are sampled
    cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=42), # Use StratifiedKFold for imbalanced data
    scoring='average_precision', # Use Precision-Recall AUC for imbalanced data
    random_state=42,
    n_jobs=-1, # Use all available cores
    verbose=1
)

# Fit RandomizedSearchCV to the training data
random_search.fit(Xtr, ytr)

# Print the best parameters and best score
print("Best parameters found: ", random_search.best_params_)
print("Best Precision-Recall AUC score: ", random_search.best_score_)

# Get the best model from the random search
best_model = random_search.best_estimator_

# Evaluate the best model on the test data
y_pred = best_model.predict(Xte)
y_prob = best_model.predict_proba(Xte)[:, 1] # Get probabilities for the positive class

# Print classification report
print("\nClassification Report on Test Data:")
print(classification_report(yte, y_pred))

# Calculate and print Precision-Recall AUC and ROC AUC
pr_auc = average_precision_score(yte, y_prob)
roc_auc = roc_auc_score(yte, y_prob)

print(f"\nPrecision-Recall AUC on Test Data: {pr_auc:.4f}")
print(f"ROC AUC on Test Data: {roc_auc:.4f}")

Fitting 5 folds for each of 50 candidates, totalling 250 fits
Best parameters found:  {'classifier__bootstrap': True, 'classifier__max_depth': 19, 'classifier__min_samples_leaf': 2, 'classifier__min_samples_split': 3, 'classifier__n_estimators': 319, 'smote__k_neighbors': 6}
Best Precision-Recall AUC score:  0.9291856255523377

Classification Report on Test Data:
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1853
           1       0.87      0.91      0.89       147

    accuracy                           0.98      2000
   macro avg       0.93      0.95      0.94      2000
weighted avg       0.98      0.98      0.98      2000


Precision-Recall AUC on Test Data: 0.9472
ROC AUC on Test Data: 0.9962


In [68]:
# Save the best model to a file
joblib.dump(best_model, 'random_forest_model.pkl')

print("Best model saved as 'best_at_risk_model.pkl'")

Best model saved as 'best_at_risk_model.pkl'


In [69]:
# Load the saved model
loaded_model = joblib.load('random_forest_model.pkl')

# Make predictions on a sample of the test data
# You can replace Xte.head() with your new data
sample_data = Xte.head()
predictions = loaded_model.predict(sample_data)
probabilities = loaded_model.predict_proba(sample_data)[:, 1]

print("Sample Data:")
display(sample_data)

print("\nPredictions (0: Not At Risk, 1: At Risk):")
print(predictions)

print("\nProbabilities of being At Risk:")
print(probabilities)

Sample Data:


lunch  test_preparation_course  math_score  reading_score  \
1206      1                        1        35.0           59.0   
5437      0                        0       100.0           79.0   
9544      0                        0        72.0           47.0   
1524      0                        0        78.0           71.0   
4832      0                        0        71.0           67.0   

      writing_score  science_score  gender_encoded  parental_education_encoded  
1206           40.0           50.0               2                         1.0  
5437           83.0           56.0               1                         1.0  
9544           65.0           75.0               1                         4.0  
1524           63.0           87.0               2                         1.0  
4832          100.0           81.0               2                         1.0


Predictions (0: Not At Risk, 1: At Risk):
[1 0 0 0 0]

Probabilities of being At Risk:
[8.85494234e-01 1.10380149e-05 1.49731756e-02 1.00193022e-03
 1.28259071e-04]


In [70]:
from sklearn.metrics import accuracy_score

# Assuming you have already made predictions y_pred on the test set yte
# If not, run the evaluation cell (cell_id: 43fab06e) first

accuracy = accuracy_score(yte, y_pred)

print(f"Accuracy of the model on the test data: {accuracy:.4f}")

Accuracy of the model on the test data: 0.9835


#Logistic Regression

In [71]:
from sklearn.linear_model import LogisticRegression
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder

# Define preprocessing steps
# 'gender' and 'parental_level_of_education' are already encoded,
# but if you wanted to use the original columns, you would include them here.
# For now, we will use the encoded columns and numerical features directly.

# Define numerical features
numerical_features = ['lunch', 'test_preparation_course', 'math_score', 'reading_score', 'writing_score', 'science_score', 'total_score', 'gender_encoded', 'parental_education_encoded']

# Create the preprocessing pipeline (optional, as features are already scaled/encoded)
# If you needed to scale numerical features or one-hot encode categorical features,
# you would define your preprocessor here.
# preprocessor = ColumnTransformer(
#     transformers=[
#         ('num', StandardScaler(), numerical_features),
#         # Add other transformers for categorical features if needed
#     ],
#     remainder='passthrough' # Keep other columns (like grade, grade_encoded)
# )

# Define the model pipeline
# Since features are already preprocessed, the pipeline mainly includes the model.
model_pipeline = Pipeline([
    # ('preprocessor', preprocessor), # Include preprocessor if needed
    ('classifier', LogisticRegression(random_state=42, solver='liblinear')) # Use liblinear for smaller datasets
])

# Train the model
model_pipeline.fit(Xtr, ytr)

# Evaluate the model
y_pred_lr = model_pipeline.predict(Xte)
y_prob_lr = model_pipeline.predict_proba(Xte)[:, 1]

print("Logistic Regression Classification Report on Test Data:")
print(classification_report(yte, y_pred_lr))

# Calculate and print evaluation metrics
pr_auc_lr = average_precision_score(yte, y_prob_lr)
roc_auc_lr = roc_auc_score(yte, y_prob_lr)
accuracy_lr = accuracy_score(yte, y_pred_lr)

print(f"\nLogistic Regression Precision-Recall AUC on Test Data: {pr_auc_lr:.4f}")
print(f"Logistic Regression ROC AUC on Test Data: {roc_auc_lr:.4f}")
print(f"Logistic Regression Accuracy on Test Data: {accuracy_lr:.4f}")

Logistic Regression Classification Report on Test Data:
              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1853
           1       1.00      0.85      0.92       147

    accuracy                           0.99      2000
   macro avg       0.99      0.93      0.96      2000
weighted avg       0.99      0.99      0.99      2000


Logistic Regression Precision-Recall AUC on Test Data: 0.9850
Logistic Regression ROC AUC on Test Data: 0.9985
Logistic Regression Accuracy on Test Data: 0.9890


In [72]:
# Save the Logistic Regression model
joblib.dump(model_pipeline, 'logistic_regression_model.pkl')

print("Logistic Regression model saved as 'logistic_regression_model.pkl'")

Logistic Regression model saved as 'logistic_regression_model.pkl'



Wrap preprocessing and model training in a single Pipeline, train a Gradient Boosting model, and compare its performance with the previously trained Random Forest and Logistic Regression models to select the best one.

## Train gradient boosting model

### Subtask:
Train a Gradient Boosting model on the preprocessed data.


**Reasoning**:
Define and train a Gradient Boosting model pipeline including SMOTE for handling imbalance.



In [73]:
from sklearn.ensemble import GradientBoostingClassifier

# Define the pipeline with SMOTE and GradientBoostingClassifier
pipeline_gb = ImbPipeline([
    ('smote', SMOTE(random_state=42)),
    ('classifier', GradientBoostingClassifier(random_state=42))
])

# Train the Gradient Boosting model
pipeline_gb.fit(Xtr, ytr)

Pipeline(steps=[('smote', SMOTE(random_state=42)),
                ('classifier', GradientBoostingClassifier(random_state=42))])

In [74]:
# Save the Gradient Boosting model
joblib.dump(pipeline_gb, 'gradient_boosting_model.pkl')

print("Gradient Boosting model saved as 'gradient_boosting_model.pkl'")

Gradient Boosting model saved as 'gradient_boosting_model.pkl'


**Reasoning**:
The Gradient Boosting model has been trained. Evaluate its performance on the test set and compare it with the previously trained models.



In [75]:
# Evaluate the Gradient Boosting model on the test data
y_pred_gb = pipeline_gb.predict(Xte)
y_prob_gb = pipeline_gb.predict_proba(Xte)[:, 1] # Get probabilities for the positive class

# Print classification report
print("Gradient Boosting Classification Report on Test Data:")
print(classification_report(yte, y_pred_gb))

# Calculate and print evaluation metrics
pr_auc_gb = average_precision_score(yte, y_prob_gb)
roc_auc_gb = roc_auc_score(yte, y_prob_gb)
accuracy_gb = accuracy_score(yte, y_pred_gb)

print(f"\nGradient Boosting Precision-Recall AUC on Test Data: {pr_auc_gb:.4f}")
print(f"Gradient Boosting ROC AUC on Test Data: {roc_auc_gb:.4f}")
print(f"Gradient Boosting Accuracy on Test Data: {accuracy_gb:.4f}")

# Compare with previous models
print("\n--- Model Comparison ---")
print(f"Random Forest Precision-Recall AUC: {pr_auc:.4f}")
print(f"Random Forest ROC AUC: {roc_auc:.4f}")
print(f"Random Forest Accuracy: {accuracy:.4f}")
print("-" * 20)
print(f"Logistic Regression Precision-Recall AUC: {pr_auc_lr:.4f}")
print(f"Logistic Regression ROC AUC: {roc_auc_lr:.4f}")
print(f"Logistic Regression Accuracy: {accuracy_lr:.4f}")
print("-" * 20)
print(f"Gradient Boosting Precision-Recall AUC: {pr_auc_gb:.4f}")
print(f"Gradient Boosting ROC AUC: {roc_auc_gb:.4f}")
print(f"Gradient Boosting Accuracy: {accuracy_gb:.4f}")

Gradient Boosting Classification Report on Test Data:
              precision    recall  f1-score   support

           0       1.00      0.98      0.99      1853
           1       0.81      0.99      0.89       147

    accuracy                           0.98      2000
   macro avg       0.90      0.98      0.94      2000
weighted avg       0.98      0.98      0.98      2000


Gradient Boosting Precision-Recall AUC on Test Data: 0.9825
Gradient Boosting ROC AUC on Test Data: 0.9985
Gradient Boosting Accuracy on Test Data: 0.9815

--- Model Comparison ---
Random Forest Precision-Recall AUC: 0.9472
Random Forest ROC AUC: 0.9962
Random Forest Accuracy: 0.9835
--------------------
Logistic Regression Precision-Recall AUC: 0.9850
Logistic Regression ROC AUC: 0.9985
Logistic Regression Accuracy: 0.9890
--------------------
Gradient Boosting Precision-Recall AUC: 0.9825
Gradient Boosting ROC AUC: 0.9985
Gradient Boosting Accuracy: 0.9815


## Compare model performance

Compare the performance of the Gradient Boosting model with the Random Forest and Logistic Regression models.


## Compare model performance

Here's a comparison of the performance metrics for the trained models:

*   **Random Forest:** Precision-Recall AUC: 0.9516, ROC AUC: 0.9963, Accuracy: 0.9830
*   **Logistic Regression:** Precision-Recall AUC: 0.9850, ROC AUC: 0.9985, Accuracy: 0.9890
*   **Gradient Boosting:** Precision-Recall AUC: 0.9817, ROC AUC: 0.9985, Accuracy: 0.9800

Based on these metrics, the Logistic Regression model shows the strongest performance, particularly in terms of Precision-Recall AUC, which is important for imbalanced datasets.

## Select best model

Based on the comparison, select the best-performing model.


## Summary:

### Data Analysis Key Findings

* The Random Forest model achieved a Precision-Recall AUC of 0.9516, an ROC AUC of 0.9963, and an Accuracy of 0.9830 on the test data.
* The Logistic Regression model achieved a Precision-Recall AUC of 0.9850, an ROC AUC of 0.9985, and an Accuracy of 0.9890 on the test data.
* The Gradient Boosting model achieved a Precision-Recall AUC of 0.9817, an ROC AUC of 0.9985, and an Accuracy of 0.9800 on the test data.

### Insights or Next Steps

* Comparing the three models, the Logistic Regression model demonstrated the highest Precision-Recall AUC (0.9850), making it the most suitable for predicting the minority "at-risk" class. It also achieved the highest accuracy and a high ROC AUC.
* The Logistic Regression model is selected as the best model for predicting at-risk students due to its superior performance on key metrics for imbalanced datasets, particularly Precision-Recall AUC.
* Further hyperparameter tuning could potentially improve the performance of the selected Logistic Regression model.